const DATABASE_NAME = '@expo-ble-darwin';
const COLLECTION_GALILEOSKYDATA = `${DATABASE_NAME}:galileoskydata`;
const COLLECTION_ETL = `${DATABASE_NAME}:etl`
const COLLECTION_TAPE = `${DATABASE_NAME}:tape`

export {
    COLLECTION_GALILEOSKYDATA,
    COLLECTION_ETL,
    COLLECTION_TAPE
}